# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler to generate a bivariate normal chain using Rcpp
#' @description A Gibbs sampler to generate a bivariate normal chain using Rcpp
#' @param N the length of chain
#' @param mu1 Initial parameters
#' @param mu2 Initial parameters
#' @param sigma1 Initial parameters
#' @param sigma2 Initial parameters
#' @param rho Initial parameters
#' @return a a Gibbs sample chain
#' @examples
#' \dontrun{
#' rbnC(1000,0,0,1,1,0.9)
#' }
#' @export
rbnC <- function(N, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22038_rbnC', PACKAGE = 'StatComp22038', N, mu1, mu2, sigma1, sigma2, rho)
}

